### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by newterminator** [KCPS/st3-theme-kcps#1]
Hey @KCPS , I just wanted to say a big THANK YOU for writing your guide on changing the scroll bars in ST3. What a huge time saver was your write-up.

**Comment by KCPS** [comment]
You're very welcome - glad you found it useful.  Thanks for taking the 
time to write.   Let me know if you have any other questions.  I haven't 
done any additional configuration in a couple of years, but I do hear 
from people such as yourself from time to time.

You can write directly to kanone@rogers.com (that's the 'K' in KCPS).

Best wishes,
         Duncan George

**Comment by newterminator** [comment]
Hi @KCPS , I appreciate your writing back. I was so glad when I found your detailed help on the matter. I had tried last year at some point to fix the scrollbars and then moved on when I didnt get a good guide...thought of igiving it a shot again this year and found yours.
